#!/bin/bash

# set -e

temp_file="./tmp.html"

for filename in $(cd ./src/scripts && find . -name "*.html"); do

  echo ${filename}

  xmllint ${filename} > /dev/null
  if [[ $? == 0 ]]; then

    echo "<template-following filename=\"${filename}\"/>" > ${temp_file}
    cat ./src/scripts/${filename} >> ${temp_file}
  else
    echo "<template-wrapper filename=\"${filename}\">" > ${temp_file}
    cat ./src/scripts/${filename} >> ${temp_file}
    echo "</template-wrapper>" >> ${temp_file}
  fi

  mv ${temp_file} ./src/scripts/${filename}

done
