#!/bin/bash

if [[ ! "${CI}" = "true" ]] # Skip the nvm stuff if running in Travis
then
  >&2 echo "==> Setting up node version"
  if [[ -f ~/.nvm/nvm.sh ]]
  then
    source ~/.nvm/nvm.sh
    nvm use
  else
    >&2 echo "Skipping the node version setup because nvm does not appear to be installed."
    >&2 echo "See https://github.com/creationix/nvm for install instructions."
    # # Try to use the other node version manager
    # if [[ -n "$(n --version)" ]]
    # then
    #   n $(cat .nvmrc) || exit 1
    # else
    #   >&2 echo "ERROR n (node version manager) is not installed globally"
    #   >&2 echo "Install it by running 'npm install --global n'"
    #   >&2 echo "(see https://www.npmjs.com/package/n )"
    #   exit 1
    # fi
  fi

  >&2 echo "Using node: $(node --version)"
  >&2 echo "Using npm: $(npm --version)"
fi

>&2 echo "==> Installing package dependencies"
npm install || exit 1
