#!/usr/bin/env bash

# Set defaults

ARCHIVE_HOST=${ARCHIVE_HOST:-archive.cnx.org}
ARCHIVE_PORT=${ARCHIVE_PORT:-80}
OPENSTAX_HOST=${OPENSTAX_HOST:-openstax.org}
OPENSTAX_PORT=${OPENSTAX_PORT:-443}
EXERCISES_HOST=${EXERCISES_HOST:-exercises.openstax.org}
EXERCISES_PORT=${EXERCISES_PORT:-443}
LEGACY_HOST=${LEGACY_HOST:-legacy.cnx.org}

# Output the settings.js to stdout
echo """\
{
  "root": "/",
  "cnxarchive": {
    "host": "${ARCHIVE_HOST}",
    "port": ${ARCHIVE_PORT}
  },
  "cnxauthoring": {
    "host": "localhost",
    "port": 8080
  },
  "openstaxcms": {
    "host": "${OPENSTAX_HOST}",
    "port": ${OPENSTAX_PORT}
  },
  "exercises": {
    "host": "${EXERCISES_HOST}",
    "port": ${EXERCISES_PORT}
  },
  "titleSuffix": " - OpenStax CNX",
  "analyticsID": "UA-7903479-1",
  "legacy": "${LEGACY_HOST}",
  "webmaster": "support@openstax.org",
  "donation": "openstaxgiving@rice.edu",
  "shortcodes": {
    "college-physics": "031da8d3-b525-429c-80cf-6c8ed997733a@8.1",
    "college-introduction-to-sociology": "afe4332a-c97f-4fc4-be27-4e4d384a32d8@7.15",
    "biology": "185cbf87-c72e-48f5-b51e-f14f21b5eabd@9.44",
    "concepts-of-biology": "b3c1e1d2-839c-42b0-a314-e119a8aafbdd@8.39",
    "anatomy-and-physiology": "14fb4ad7-39a1-4eee-ab6e-3ef2482e3e22@6.19",
    "introductory-statistics": "30189442-6998-4686-ac05-ed152b91b9de@17.20"
  },
  "accountProfile": "https://accounts.cnx.org/profile",
  "cnxSupport": "https://openstax.secure.force.com/help",
  "defaultLicense": {
    "code": "by"
  }
}
"""
