#!/bin/bash
set -e

npm test

# Check that l20n starts up
# Do not run on Travis because the test has not been fixed for Travis
if [[ ${TRAVIS} != 'true' ]]; then
  npm run-script dist
  PATH="${PATH}:$(npm bin)" node ./test/verify-l20n.js
fi
